### ISSUE TITLE
Train mnist On GPU failed: RuntimeError: CUDA error: invalid device ordinal, with example code: examples/pytorch/mnist/cnn_train.py

### ISSUE THREAD

**Issue by cooper190113** [intelligent-machine-learning/dlrover#675]
**pod status:**
![image](https://github.com/intelligent-machine-learning/dlrover/assets/851243/f003da66-747a-4b61-aaab-af5e3816f9b1)

**work pod error logs:**
![image](https://github.com/intelligent-machine-learning/dlrover/assets/851243/301ca3eb-f6af-41bb-bc33-abd62e473436)

**code: examples/pytorch/mnist/cnn_train.py**
![70e7726965d5c967ea565c499ee6eb42_32435](https://github.com/intelligent-machine-learning/dlrover/assets/851243/89b296ca-ecca-40e7-b911-51bbbabc00d1)

**gpu**
![image](https://github.com/intelligent-machine-learning/dlrover/assets/851243/74b23312-6ed2-4013-b058-eb81bebf3e10)

**Comment by workingloong** [comment]
You may need to turn up the memory of resource.

**Comment by cooper190113** [comment]
> You may need to turn up the memory of resource.

Increase the resource memory of CPU or GPU?


Other：
Does DLRover support multi-machine and multi-card training? How to configure and deploy YAML?

**Comment by workingloong** [comment]
> > You may need to turn up the memory of resource.
> 
> Thanks，problem has been solved。
> 
> Other： 1、Does DLRover support multi-machine and multi-card training? How to configure and deploy YAML? 2、Is there an open communication group？ such as WeChat, DingTalk, etc.

Q1: Yes. You only need to configure GPU in the resource like
```
         resources:
                limits:
                  cpu: "8"
                  memory: 16Gi
                  nvidia.com/gpu: 2 
                requests:
                  cpu: "4"
                  memory: 16Gi
                  nvidia.com/gpu: 2
```

There is an example to train nanogpt with multiple GPUs int the [tutorial](https://github.com/intelligent-machine-learning/dlrover/blob/master/docs/tutorial/torch_ddp_nanogpt.md).

Q2: Yes, You can add SOFAGirl to friends in WeChat and she will push you into the WeChat group (DLRover社区交流群)。
